<a href="https://colab.research.google.com/github/sf-rahul/Tensorflow/blob/master/Recurrent_nueral_network.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
#rnnn
from __future__ import absolute_import, division, print_function, unicode_literals

try:
  # %tensorflow_version only exists in Colab.
  %tensorflow_version 2.x
except Exception:
  pass
import tensorflow as tf

import numpy as np
import os
import time

tf.random.set_seed(1)

TensorFlow 2.x selected.


In [0]:
#function to create time series data of length n_steps
#input to the rnn is [batch_size, time steps , dimensionality]
#a time series is cosistting of timesteps and value (univariate or multivariate)
def generate_time_series(batch_size,n_steps):
  freq1,freq2,offset1,offset2 = np.random.rand(4,batch_size,1)#4 random array of shape (batch_size,1)
  time = np.linspace(0,1,n_steps)
  series = 0.5  * np.sin((time-offset1) * (freq1*10+10)) #wave1
  series+= 0.2 * np.sin((time-offset2) * (freq2*20 +20)) #+wave2
  series +=0.1*(np.random.rand(batch_size,n_steps) - 0.5) #+noise
  print(series)
  return series[...,np.newaxis].astype(np.float32)




In [42]:
generate_time_series(4,5)
np.newaxis

[[ 0.04704501  0.12333699 -0.29844258  0.14590388  0.12549437]
 [-0.68745107 -0.04065135  0.19740275  0.40778712 -0.10071406]
 [-0.62900131  0.23510306  0.18915201 -0.0835302   0.31807856]
 [ 0.10320698 -0.27524725 -0.09219838  0.33668047  0.11256098]]
